Repository P-RCollaboration/CoreComponents, pull requests merged in 2021-03, with the labels that each got.

#1 Added initial version for component bootstraper
  src/libraries/vuejs2.boostraper.js
Labels: enhancement

#2 Fix parse styles
  src/libraries/vuejs2.boostraper.js
Labels: bug

#3 Added hello world example and dependency resolver
  src/examples/helloworld/App.vue
  src/examples/helloworld/index.html
  src/libraries/resolveDependencies.js
  src/libraries/vuejs2.boostraper.js
  src/states/ButtonState.vue
  src/views/bootstrap/ButtonView.vue
Labels: enhancement

#4 > Fix request batching issue
  index.html
  src/libraries/vuejs2.boostraper.js
Labels: bug

#5 Change path to components in App.vue
  src/examples/helloworld/App.vue
Labels: bug

#8 Added CheckBox state and view for bootstrap
  src/examples/helloworld/App.vue
  src/states/CheckBoxState.vue
  src/views/bootstrap/CheckBoxView.vue
Labels: enhancement

#10 Added new state CheckBoxTriState
  src/examples/helloworld/App.vue
  src/libraries/vuejs2.boostraper.js
  src/states/CheckBoxState.vue
  src/states/CheckBoxTriState.vue
  src/views/bootstrap/CheckBoxView.vue
Labels: Improvment

#9 Implemented presentor and views for bootstrap and md
  src/examples/helloworld/App.vue
  src/states/ListBoxState.vue
  src/views/bootstrap/ListBoxView.vue
  src/views/material/ListBoxView.vue
Labels: enhancement

#13 Added validate host
  src/examples/helloworld/App.vue
  src/libraries/vuejs2.boostraper.js
  src/states/CheckBoxState.vue
  src/states/CheckBoxTriState.vue
  src/states/FontIconState.vue
  src/states/NumberBoxState.vue
  src/states/TextAreaState.vue
  src/states/TextBoxState.vue
  src/states/ValidateHost.vue
  src/views/bootstrap/NumberBoxView.vue
  src/views/fontawesome/FontIconView.vue
Labels: enhancement

#14 Dropdown component
  src/examples/helloworld/App.vue
  src/states/DropdownState.vue
  src/views/bootstrap/DropdownView.vue
Labels: enhancement
